apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ca-sfd
  namespace: sfd-dev
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      volume: ca-sfd
  volumeName: ca-sfd