apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: peer1-sfd-tls
  namespace: sfd-dev
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      volume: peer1-sfd-tls
  volumeName: peer1-sfd-tls
