apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: peer0-sfd-production
  namespace: sfd-dev
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      volume: peer0-sfd-production
  volumeName: peer0-sfd-production
