apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sfd-orderer1
  namespace: sfd-dev
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      volume: sfd-orderer1
  volumeName: sfd-orderer1