apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    volume: ca-sfd
  name: ca-sfd
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    path: /root_vdm_11/DNN1PAASDF001/paasds/sfd/BB_orderer_sfd/ca_sfd
    server: '[2801:8e:802::1]'
  persistentVolumeReclaimPolicy: Retain