apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    volume: peer0-sfd-tls
  name: peer0-sfd-tls
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    path: /root_vdm_11/DNN1PAASDF001/paasds/sfd/BB_orderer_sfd/desenv.bb.com.br/crypto-config/peerOrganizations/desenv.bb.com.br/peers/peer0-sfd.desenv.bb.com.br/tls
    server: '[2801:8e:802::1]'
  persistentVolumeReclaimPolicy: Retain