apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    volume: sfd-desenv-channel-artifacts
  name: sfd-desenv-channel-artifacts
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    path: '/root_vdm_11/DNN1PAASDF001/paasds/sfd/BB_orderer_sfd/desenv.bb.com.br/channel-artifacts'
    server: '[2801:8e:802::1]'
  persistentVolumeReclaimPolicy: Retain