apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: site1
  name: fabric-kafka-0
  namespace: sfd-dev
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: site1
    deploymentconfig: fabric-kafka-0
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: site1
        deploymentconfig: fabric-kafka-0
    spec:
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          valueFrom:
            configMapKeyRef:
              name: sfd-config
              key: bb_kafka0_broker_id
        - name: KAFKA_ADVERTISED_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: sfd-config
              key: bb_kafka0_advertised_hostname
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          valueFrom:
            configMapKeyRef:
              name: sfd-config
              key: bb_kafka_listener_security_protocol_map
        - name: KAFKA_LISTENERS
          valueFrom:
            configMapKeyRef:
              name: sfd-config
              key: bb_kafka0_listeners
        - name: KAFKA_ADVERTISED_LISTENERS
          valueFrom:
            configMapKeyRef:
              name: sfd-config
              key: bb_kafka0_advertise_listener
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          valueFrom:
            configMapKeyRef:
              name: sfd-config
              key: bb_kafka_inter_broker_listener_name
        - name: KAFKA_AUTO_LEADER_REBALANCE_ENABLE
          valueFrom:
            configMapKeyRef:
              name: sfd-config
              key: bb_kafka_auto_leader_rebalance_enable
        - name: KAFKA_ZOOKEEPER_CONNECT
          valueFrom:
            configMapKeyRef:
              name: sfd-config
              key: bb_kafka_zookeeper_connect
        - name: KAFKA_MESSAGE_MAX_BYTES
          valueFrom:
            configMapKeyRef:
              name: sfd-config
              key: bb_kafka_message_max_bytes
        - name: KAFKA_REPLICA_FETCH_MAX_BYTES
          valueFrom:
            configMapKeyRef:
              name: sfd-config
              key: bb_kafka_replica_fetch_max_bytes
        - name: KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE
          valueFrom:
            configMapKeyRef:
              name: sfd-config
              key: bb_kafka_unclean_leader_election_enable
        - name: KAFKA_LOG_RETENTION_MS
          valueFrom:
            configMapKeyRef:
              name: sfd-config
              key: bb_kafka_log_retention_ms
        - name: KAFKA_MIN_INSYNC_REPLICAS
          valueFrom:
            configMapKeyRef:
              key: bb_kakfa_kafka_min_insync_replicas
              name: sfd-config
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          valueFrom:
            configMapKeyRef:
              name: sfd-config
              key: bb_kafka_default_replication_factor
        image: harbor.servicos.bb.com.br/fabric-network/hyperledger/fabric-kafka:latest
        imagePullPolicy: IfNotPresent
        name: fabric-kafka-0
        ports:
        - containerPort: 9092
          protocol: TCP
        - containerPort: 9093
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: dxl1pscnd001.dispositivos.bb.com.br
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
