apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: fabric-orderer-0
  name: fabric-orderer-0
  namespace: sfd-dev
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: 7050-tcp
    nodePort: 30400
    port: 7050
    protocol: TCP
    targetPort: 7050
  selector:
    deploymentconfig: fabric-orderer-0
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
