apiVersion: v1
kind: Service
metadata:
  labels:
    app: site3
  name: kafka5-node
  namespace: sfd-dev
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: 30305-tcp
    nodePort: 30305
    port: 30305
    protocol: TCP
    targetPort: 30305
  selector:
    deploymentconfig: fabric-kafka-5
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
