apiVersion: v1
kind: Service
metadata:
  labels:
    app: site3
  name: kafka4-node
  namespace: sfd-dev
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: 30304-tcp
    nodePort: 30304
    port: 30304
    protocol: TCP
    targetPort: 30304
  selector:
    deploymentconfig: fabric-kafka-4
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
