apiVersion: v1
kind: Service
metadata:
  labels:
    app: site1
  name: kafka0-node
  namespace: sfd-dev
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: 30300-tcp
    nodePort: 30300
    port: 30300
    protocol: TCP
    targetPort: 30300
  selector:
    deploymentconfig: fabric-kafka-0
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
