apiVersion: v1
kind: Service
metadata:
  labels:
    app: site2
  name: kafka2-node
  namespace: sfd-dev
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: 30302-tcp
    nodePort: 30302
    port: 30302
    protocol: TCP
    targetPort: 30302
  selector:
    deploymentconfig: fabric-kafka-2
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
