apiVersion: v1
kind: Service
metadata:
  labels:
    app: site2
  name: kafka3-node
  namespace: sfd-dev
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: 30303-tcp
    nodePort: 30303
    port: 30303
    protocol: TCP
    targetPort: 30303
  selector:
    deploymentconfig: fabric-kafka-3
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
