apiVersion: v1
kind: Service
metadata:
  labels:
    deploymentconfig: peer1-sfd
  name: peer1-sfd
  namespace: sfd-dev
spec:
  ports:
  - name: 7051-tcp
    port: 7051
    protocol: TCP
    targetPort: 7051
    NodePort: 30201
  - name: 7052-tcp
    port: 30223
    protocol: TCP
    targetPort: 30223
    NodePort: 30223
  - name: 7053-tcp
    port: 7053
    protocol: TCP
    targetPort: 7053
  selector:
    deploymentconfig: peer1-sfd
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
